head:
   favicon: "https://i.loli.net/2020/10/13/TCu5AoPrRHVfgXc.jpg" #  the favicon
   high_res_favicon: "https://i.loli.net/2020/10/13/SqOWKY89lAZzcTF.png" #  the favicon using high quality format
   apple_touch_icon: "https://i.loli.net/2020/10/13/SqOWKY89lAZzcTF.png" # the iOS Home button icon
   keywords: "blog 4 Neuifo record essay" #  the site keywords

uiux:
   android_chrome_color: "#eeeeee" #  the color of the Chrome address bar
   nprogress_color: "#29d" #  the color of the top loading progress bar
   nprogress_buffer: 200 # the top loading progress bar buffers
   meng: false # meng

background:
   purecolor: "#000000" # the background color

img:
   avatar: "https://i.loli.net/2020/10/13/TCu5AoPrRHVfgXc.jpg" # your avatar

card:
   card_shadow: 1 # card shadow (0-24), 0 is not displayed
   card_hoverable: false # When the hover to deepen the shadow

many_authors: false

sns_share: # SNS Share Switch
   twitter: true
   facebook: false
   googleplus: false
   weibo: true
   linkedin: false
   qq: true
   telegram: true

comment:
  used: "disqus" # disqus,livere,gitment,valine
  # disqus config
  disqus_shortname: "neuifo" # Your disqus
  disqus_button: true # disqus load button
  disqus_proxy: false # # disqus proxy(Do not use)
  disqus_proxy_url: "" # (Do not use)
  disqus_api_key: "" # (Do not use)
  # livere config
  livere_type: 'city'
  livere_data_uid: ''
  # gitment config
  owner: ""
  repo: ""
  client_id: ""
  client_secret: ""
  #valine config
  valine_notify: false #mail notifier
  valine_verify: false #validation code
  valine_app_id: ''
  valine_app_key: ''
  valine_placeholder: "这个人很懒，什么都不愿意写"

prism:
  themes: prism-okaidia
  components:
    - bash
  plugins:

mathjax: true

google_analytics: ""  # google analytics code

baidu_site_verification: ""  # baidu site verification code
google_site_verification: ""  # google search console verification code

baidu_auto_push: false  # if you used baidu auto push to commit links

lang: ""  # lang

deploy: "" # if you used coding pages

custom_css: "" # Use the assets/css/customCss.css

custom_js: "" # Use the assets/js/customJS.js
